credentials:
  usernames:
    user:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$XHqZsLg59L6xrPu34yXdW.gxaJHDowwfjOY7CwkA4jw//znQQfOqC
    admin:
      email: asmith@gmail.com
      name: Adam Smith
      password: $2b$12$RPpHTilf.sEKTEDRzJK/Ku55tN3Gd1RncslEZOHGizAQYVA.xJnTu
cookie:
  expiry_days: 3
  key: gradproject
  name: nuharips